### ISSUE TITLE
BUG in production code: predict function Z scores 

### ISSUE THREAD

**Issue by alegiac95** [amarquand/PCNtoolkit#83]
Hi, I have checked and rechecked with @LuciaMaccioni the last version of your code and after commit 0c4d0c7 we think you might have some bug in the `predict()` function in the file `normative.py`. 

In particular you have that at lines `770-773`:
```python
Y = Y[:, m]
if meta_data:
    mY = mY[m]
    sY = sY[m]
```
which is subsetting the `Y` matrix on just the last model estimated. In addition the following ```if``` statement,  the variables ```mY[m]``` and ```sY[m]``` are referenced to ```m``` while ```mY``` and ```sY``` are both lists of arrays, and the code throws an ```IndexError```. 

Since the ``Y`` is used to calculate the ``Z`` scores this could be an issue.

In addition on line `489` in the `estimate()` function, where you have
```python 
mY=np.std(yw), sY=np.mean(yw)
```
aren't those (at least from the names) inverted?

**Comment by amarquand** [comment]
Hi - Thanks for pointing this out. You are correct that this is a bug. We have fixed it in the development branch and will push the changes to the main branch in the coming days. In the mean time and depending on what you are doing you can either take a release just before that change (the changes are minor) or you can take the version from the dev branch, where it should be fixed. 

Thanks!
Andre.

**Comment by tabeastraeten** [comment]
Hi, I think you might still have a bug in the predict() function in version `0.25`.

At lines `772-774` the code says:
```
if meta_data:
        mY = mY[models]
        sY = sY[models]
```
`mY` and `sY` are indexed by `models` which is a range of the number of estimated models but `mY` and `sY ` are lists containing an array for each split. Thus, the code still throws a `Type Error: list indices must be integers or slices, not range` when passing more than one estimated model to the function. You might also need to change the index of `mY` and `sY` at line `789` if the arrays were already extracted at lines '772-774'.

In addition, `fold` is listed as a keyword argument in the predict()-function but it seems like you do not consider `fold` when calculating the outputs. I think that might lead to wrong numbers when using cross validation. 

Thank you very much!

**Comment by amarquand** [comment]
Thanks for pointing this out. We will take a look and try to correct for the next release.

**Comment by amarquand** [comment]
Hi - I have been looking at this and I would like to ask if you are trying to use predict() in the context of cross-validation? If so, that is not really intended usage since it would then be necessary to make a prediction for each fold, which is better done using the estimate() function or by wrapping separately using fit() and predict(). Could you please confirm how you are trying to run this?

**Comment by tabeastraeten** [comment]
Hi, thanks for taking a look at the issue. I am not using cross-validation and just mentioned the last point after "In addition,..." to prevent a potential future issue. It might be a mistake that you can specify which cross-validation fold to use in the predict() function but fold is not considered when extracting values from the meta data file. Instead, variables from the meta data file are always indexed by 0, the default value for train-test split.

The explained Index Error at lines 773-774 occurs when using train-test split and passing more than one estimated model to the function.

**Comment by tabeastraeten** [comment]
Hi, it works for me too but I have two further comments.

1) You might need to remove the index of `mY` and `sY` at line 798 to pass the values of all estimated models to the evaluate() function as the arrays are already extracted at lines 773-774.
2) To be consistent you might also need to replace the index '0' with 'fold' when indexing meta data variables at other lines. As I am not using cross-validation, I did not try to run the function with a specified fold.

Thank you for debugging and providing the tool.

**Comment by amarquand** [comment]
Thanks for pointing these out as well. These are fixed and will be included in the upcoming release
